version:          "Tue 27 Aug 2024 19:00"
copyright:        "2024-2024"
title:            "Index Tafsir Al-Azhar HAMKA"
author:           "Abdul Latip"
address:          "Ternate, 99772."
description:
                  "Index Quran Tafsir Al-Azhar HAMKA"
disclaimer:
                  "I have spoken!"
tagline:          
                  "Index Quran Tafsir Al-Azhar HAMKA"
keywords:         Index, Quran, Tafsir, Al-Azhar, HAMKA
navbarlinks:
- navbar:         "Home"
  link:           "/"
- navbar:         "J1"
  link:           "001.html"
- navbar:         "J2"
  link:           "002.html"
- navbar:         "J3"
  link:           "003.html"
- navbar:         "J4"
  link:           "004.html"
- navbar:         "J5"
  link:           "005.html"
- navbar:         "J6"
  link:           "006.html"
- navbar:         "J7"
  link:           "007.html"
- navbar:         "J8"
  link:           "008.html"
- navbar:         "J9"
  link:           "009.html"
- navbar:         "PDF"
  link:           "https://rms46.vlsm.org/2/230.pdf"
- navbar:         "GitHub"
  link:           "https://github.com/sdnbhd/indexquran/"
- navbar:         "About"
  link:           "/ABOUT/"
- navbar:         "GitHub Page"
  link:           "https://sdnbhd.github.io/indexquran/"
lang:             "en-US"
sitemap:          "true"
markdown:         "kramdown"
urlweb:           "https://sdnbhd.github.io/indexquran/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/sdnbhd/indexquran/"
google_analytics: "G-KPSLWHN6H7"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata

